---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydata-pvc
  namespace: myshare
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 800Gi
