---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rook-repo
  namespace: flux
spec:
  interval: 10m
  url: https://charts.rook.io/release
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: minio-op
#   namespace: minio-operator
# spec:
#   interval: 10m
#   chart:
#     spec:
#       chart: operator
#       sourceRef:
#         kind: HelmRepository
#         name: minio-repo
#         namespace: flux
#       interval: 10m
#   values:
#     operator:
#       replicaCount: 1
