---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rook-repo
  namespace: flux
spec:
  interval: 10m
  url: https://charts.rook.io/release
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: rook-op
#   namespace: rook-ceph
# spec:
#   interval: 10m
#   chart:
#     spec:
#       chart: rook-ceph
#       version: "v1.18.8"
#       sourceRef:
#         kind: HelmRepository
#         name: rook-repo
#         namespace: flux
#       interval: 10m
#   values:
#     image:
#       repository: docker.m.daocloud.io/rook/ceph
#     csi:
#       provisionerReplicas: 1
#       csiCephFSPluginResource: |
#         - name : driver-registrar
#           resource:
#             requests:
#               memory: 10Mi
#             limits:
#               memory: 256Mi
#         - name : csi-cephfsplugin
#           resource:
#             requests:
#               memory: 10Mi
#             limits:
#               memory: 1Gi
#         - name : liveness-prometheus
#           resource:
#             limits:
#               memory: 256Mi    
#       csiCephFSProvisionerResource: |
#         - name : csi-provisioner
#           resource:
#             requests:
#               memory: 10Mi
#             limits:
#               memory: 256Mi
#         - name : csi-resizer
#           resource:
#             requests:
#               memory: 10Mi
#             limits:
#               memory: 256Mi
#         - name : csi-attacher
#           resource:
#             requests:
#               memory: 10Mi
#             limits:
#               memory: 256Mi
#         - name : csi-snapshotter
#           resource:
#             requests:
#               memory: 10Mi
#             limits:
#               memory: 256Mi
#         - name : csi-cephfsplugin
#           resource:
#             requests:
#               memory: 10Mi
#             limits:
#               memory: 1Gi
#         - name : liveness-prometheus
#           resource:
#             requests:
#               memory: 10Mi
#             limits:
#               memory: 256Mi    
#       csiRBDPluginResource: |
#         - name : driver-registrar
#           resource:
#             requests:
#               memory: 10Mi
#             limits:
#               memory: 256Mi
#         - name : csi-rbdplugin
#           resource:
#             requests:
#               memory: 10Mi
#             limits:
#               memory: 1Gi
#         - name : liveness-prometheus
#           resource:
#             requests:
#               memory: 10Mi
#             limits:
#               memory: 256Mi    
#       csiRBDProvisionerResource: |
#         - name : csi-provisioner
#           resource:
#             requests:
#               memory: 10Mi
#             limits:
#               memory: 256Mi
#         - name : csi-resizer
#           resource:
#             requests:
#               memory: 10Mi
#             limits:
#               memory: 256Mi
#         - name : csi-attacher
#           resource:
#             requests:
#               memory: 10Mi
#             limits:
#               memory: 256Mi
#         - name : csi-snapshotter
#           resource:
#             requests:
#               memory: 10Mi
#             limits:
#               memory: 256Mi
#         - name : csi-rbdplugin
#           resource:
#             requests:
#               memory: 10Mi
#             limits:
#               memory: 1Gi
#         - name : csi-omap-generator
#           resource:
#             limits:
#               memory: 1Gi
#         - name : liveness-prometheus
#           resource:
#             requests:
#               memory: 10Mi      
#             limits:
#               memory: 256Mi      
