---
apiVersion: v1
kind: Namespace
metadata:
  name: kagent
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k-crd
  namespace: kagent
spec:
  chartRef:
    kind: OCIRepository
    name: kagent
    namespace: flux
  interval: 10m
  values: {}
