---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: nginx
      version: '13.2.23'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux
      interval: 10m
  values:
    replicaCount: 2