---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: myshare
spec:
  interval: 10m
  chart:
    spec:
      chart: nginx
      version: '13.2.23'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux
      interval: 10m
  values:
    replicaCount: 1
    containerPorts:
      http: 80
      https: 443
    global:
      imageRegistry: docker.m.daocloud.io
      security:
        allowInsecureImages: true
    image:
      repository: "library/nginx"
      tag: 1.25.3      
