---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ks
  namespace: kube-system
spec:
  chart:
    spec:
      chart: ./charts/
      sourceRef:
        kind: GitRepository
        name: kube-stack-charts
        namespace: flux
  interval: 10m
  values: {}